### ISSUE TITLE
[SCAN] sub-01_ses-091

### ISSUE THREAD

**Issue by me-pic** [courtois-neuromod/friends#100]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

**During set-up**
PPG, ECG, RSP good. EDA a bit noisy...

### task-friends_run-01 segment

s7e23a

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-01 notes

**Eye-tracker**
A lot of Cs for Conf, although due to some time constraints RA decided not to redo the calibration. Participant seemed to have moved during the run. The eye was not centered within the eye-tracker box anymore..

**Physio**
Some noise affecting all signals (likely motion artefacts)
RSP belt might be a bit too loose (some long troughs)
Some fluctuation in the EDA signals
Clear R peaks on ECG waveform
Amplitude of PPG a bit smaller than usual (scanning room a bit cold today)

### task-friends_run-02 segment

s7e23b

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-02 notes

**Eye-tracker**
Validation good, mostly As and Bs

**Physio**
Same as previous runs
Small PPG amplitude
Some motion artefacts in the signals

### task-friends_run-03 segment

s7e23c

### task-friends_run-03 completion

- [X] series was completed.

### task-friends_run-03 notes

**Eye-tracker**
Mostly As and Bs for eye-tracker validation. Lost the red dot in the Pupil Capture - World window during the run

**Physio**
Same as previous run

### task-friends_run-04 segment

s7e23d

### task-friends_run-04 completion

- [X] series was completed.

### task-friends_run-04 notes

**Eye-tracker**
Almost just As for validation

**Physio**
Same as previous run

### task-friends_run-05 completion

- [ ] series was completed.

### task-friends_run-06 completion

- [ ] series was completed.

### task-friends_run-07 completion

- [ ] series was completed.

### task-friends_run-08 completion

- [ ] series was completed.

### task-friends_run-09 completion

- [ ] series was completed.

### task-friends_run-10 completion

- [ ] series was completed.
