### ISSUE TITLE
[SCAN] sub-05_ses-055

### ISSUE THREAD

**Issue by FrancoisPgm** [courtois-neuromod/friends#101]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### task-friends_run-01 segment

s7e16b

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-02 segment

s7e16c

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-03 segment

s7e17a

### task-friends_run-03 completion

- [X] series was completed.

### task-friends_run-04 completion

- [ ] series was completed.

### task-friends_run-05 completion

- [ ] series was completed.

### task-friends_run-06 completion

- [ ] series was completed.

### task-friends_run-07 completion

- [ ] series was completed.

### task-friends_run-08 completion

- [ ] series was completed.

### task-friends_run-09 completion

- [ ] series was completed.

### task-friends_run-10 completion

- [ ] series was completed.
