### ISSUE TITLE
[SCAN] sub-05_ses-056

### ISSUE THREAD

**Issue by RainyFields** [courtois-neuromod/friends#102]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### task-friends_run-01 segment

s07e17b

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-01 notes

the eyecalibration validation after the break returns distances with all Cs

### task-friends_run-02 segment

s07e18a

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-03 segment

s07e18b

### task-friends_run-03 completion

- [X] series was completed.

### task-friends_run-04 segment

s07e19a

### task-friends_run-04 completion

- [X] series was completed.

### task-friends_run-05 segment

s07e19b

### task-friends_run-05 completion

- [X] series was completed.

### task-friends_run-06 completion

- [ ] series was completed.

### task-friends_run-07 completion

- [ ] series was completed.

### task-friends_run-08 completion

- [ ] series was completed.

### task-friends_run-09 completion

- [ ] series was completed.

### task-friends_run-10 completion

- [ ] series was completed.
