### ISSUE TITLE
[SCAN] sub-05_ses-057

### ISSUE THREAD

**Issue by me-pic** [courtois-neuromod/friends#103]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

All physio signals were ok during the setup.
EDA gain was set at 2 on the amplifier.

### task-friends_run-01 segment

s7e20a

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-01 issues

physio signal quality issue

### task-friends_run-01 notes

**Eye-tracker calibration**
Good

**Physio**
ECG got really noisy once the participant entered the bore, and even more corrupted when the sequence started. Some motion related artefacts during the run.
PPG also noisy..
Some long plateaus in the RSP signal
EDA not fluctuating much (potentially not enough gel on the electrodes, did not fix it due to some time constraint with this acquisition)

### task-friends_run-02 segment

s7e20b

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-02 issues

physio signal quality issue

### task-friends_run-02 notes

**Eye-tracker calibration**
Good

**Physio**
Between run-01 and run-02: really small R peaks. PPG looked ok, noisy EDA, some long plateau on the RSP waveform
During run-02: same comment as previous run

### task-friends_run-03 segment

s7e21a

### task-friends_run-03 completion

- [X] series was completed.

### task-friends_run-03 issues

sleep, physio signal quality issue

### task-friends_run-03 notes

Participant fell asleep during the run

**Eye-tracker calibration**
Participant had their eyes closed during the beginning of the calibration. A lot of Cs during the calibration (RA did not restart the eye-tracker calibration due to time constraints)

**Physio**
Same comments as previous runs

### task-friends_run-04 segment

s7e21b

### task-friends_run-04 completion

- [X] series was completed.

### task-friends_run-04 issues

physio signal quality issue

### task-friends_run-04 notes

**Eye-tracker calibration**
Good

**Physio**
Same comments as previous run

### task-friends_run-05 segment

s7e22a

### task-friends_run-05 completion

- [X] series was completed.

### task-friends_run-05 issues

physio signal quality issue

### task-friends_run-05 notes

**Eye-tracker calibration**
Good

**Physio**
Same comments as previous run

### task-friends_run-06 segment

s7e22b

### task-friends_run-06 completion

- [X] series was completed.

### task-friends_run-06 issues

physio signal quality issue

### task-friends_run-06 notes

**Eye-tracker calibration**
Good

**Physio**
PPG and ECG really noisy
RSP ok
Some small fluctuations on the EDA waveform

### task-friends_run-07 segment

s7e23a

### task-friends_run-07 completion

- [X] series was completed.

### task-friends_run-07 issues

physio signal quality issue

### task-friends_run-07 notes

**Eye-tracker calibration**
Good

**Physio**
Between runs: small PPG amplitude
During there run: same comments as previous run

### task-friends_run-08 segment

s7e23b

### task-friends_run-08 completion

- [X] series was completed.

### task-friends_run-08 issues

physio signal quality issue

### task-friends_run-08 notes

**Eye-tracker calibration**
Good

**Physio**
Same comments as previous run. 
Motion artefacts around the beginning and the end of the run
Some fluctuations on the EDA waveform

### task-friends_run-09 segment

s7e23c

### task-friends_run-09 completion

- [X] series was completed.

### task-friends_run-09 notes

**Eye-tracker calibration**
Good. Some motion during the run (head moved)

**Physio**
Some motion artefacts throughout the run
Small PPG and ECG amplitude
RSP ok
some fluctuations in the EDA signal

### task-friends_run-10 segment

s7e23d

### task-friends_run-10 completion

- [X] series was completed.

### task-friends_run-10 issues

physio signal quality issue

### task-friends_run-10 notes

**Eye-tracker calibration**
Good. 

**Physio**
Some motion artefacts
Same comments as previous run
