### ISSUE TITLE
[SCAN] sub-06_ses-068

### ISSUE THREAD

**Issue by maelleF** [courtois-neuromod/friends#56]
### Setup

- [ ] biopac
- [ ] sensimetrics
- [ ] eyetracker

### task-friends_run-01 segment

s7e22a

### task-friends_run-01 completion

- [ ] series was completed.

### task-friends_run-02 completion

- [ ] series was completed.

### task-friends_run-03 completion

- [ ] series was completed.

### task-friends_run-04 completion

- [ ] series was completed.

### task-friends_run-05 completion

- [ ] series was completed.

### task-friends_run-06 completion

- [ ] series was completed.
