### ISSUE TITLE
[SCAN] sub-01_ses-077

### ISSUE THREAD

**Issue by maelleF** [courtois-neuromod/friends#83]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

PPG ok
ECG ok, slightly noisy but R peak visible most of the time (2,5mV / -2mV)
respiration ok
No signal for EDA

### task-friends_run-01 segment

s7e08a

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-02 completion

- [ ] series was completed.

### task-friends_run-03 completion

- [ ] series was completed.

### task-friends_run-04 completion

- [ ] series was completed.

### task-friends_run-05 completion

- [ ] series was completed.

### task-friends_run-06 completion

- [ ] series was completed.

### task-friends_run-07 completion

- [ ] series was completed.

### task-friends_run-08 completion

- [ ] series was completed.

### task-friends_run-09 completion

- [ ] series was completed.

### task-friends_run-10 completion

- [ ] series was completed.
