### ISSUE TITLE
[SCAN] sub-05_ses-051

### ISSUE THREAD

**Issue by FrancoisPgm** [courtois-neuromod/friends#85]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### task-friends_run-01 segment

s7e9b

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-01 issues

physio signal quality issue

### task-friends_run-01 notes

the GSR sometimes dropped to 0. The signal is very unstable and alternates between realitstic values (~12) and flat 0.

### task-friends_run-02 segment

s7e10a

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-03 segment

s7e10b

### task-friends_run-03 completion

- [X] series was completed.

### task-friends_run-03 notes

Participant had their eyes closed during eyetracker validation at the end of the run.

### task-friends_run-04 segment

s7e11a

### task-friends_run-04 completion

- [X] series was completed.

### task-friends_run-05 segment

s7e11b

### task-friends_run-05 completion

- [X] series was completed.

### task-friends_run-06 completion

- [ ] series was completed.

### task-friends_run-07 completion

- [ ] series was completed.

### task-friends_run-08 completion

- [ ] series was completed.

### task-friends_run-09 completion

- [ ] series was completed.

### task-friends_run-10 completion

- [ ] series was completed.
