### ISSUE TITLE
[SCAN] sub-01_ses-080

### ISSUE THREAD

**Issue by me-pic** [courtois-neuromod/friends#86]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

During setup:
Re-adjustment of the respiratory belt; it was a bit too loose
Clear PPG waveform
ECG ok although amplitude a bit small
Fluctuation in the EDA waveform following contraction of the fists; EDA gain was set at 2 microsiemens

### task-friends_run-01 segment

e10a

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-01 notes

**Eye-tracking**
Add to rerun the eyetracker calibration; Conf not good

**Physio**
Amplitude of R peaks small compared to amplitude of noise
RESP looked good
Some fluctuations in the EDA waveform (amplitude a bit low; around 3 microsiemens)

### task-friends_run-02 segment

e10b

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-02 notes

**Eye-tracking**
Add to rerun the eyetracker calibration; Conf not good

**Physio**
Some fluctuations in the amplitude of the PPG signal
Amplitude of R peaks a bit small
RESP looked ok
Some fluctuations on the EDA waveform

### task-friends_run-03 segment

e11a

### task-friends_run-03 completion

- [X] series was completed.

### task-friends_run-03 notes

**Eye-tracking**
Few Cs for Conf

**Physio**
Same as previous runs

### task-friends_run-04 segment

e11b

### task-friends_run-04 completion

- [X] series was completed.

### task-friends_run-04 notes

**Eye-tracking**
Validation: mostly As

**Physio**
Small PPG amplitude
Amplitude of R peaks a bit small compared to amplitude of noise
RESP looked ok
Some small fluctuations on the EDA waveform

Some motion mid run

### task-friends_run-05 segment

e12a

### task-friends_run-05 completion

- [X] series was completed.

### task-friends_run-05 notes

**Eye-tracking**
Conf not really good during calibration; participant's eyelid was covering a bit of the pupil. We proceeded with the run given time.

**Physio**
Same as previous run
Small PPG amplitude

### task-friends_run-06 completion

- [ ] series was completed.

### task-friends_run-07 completion

- [ ] series was completed.

### task-friends_run-08 completion

- [ ] series was completed.

### task-friends_run-09 completion

- [ ] series was completed.

### task-friends_run-10 completion

- [ ] series was completed.
