### ISSUE TITLE
[SCAN] sub-01_ses-086

### ISSUE THREAD

**Issue by maelleF** [courtois-neuromod/friends#93]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

PPG ok
ECG noisy after entering scan, R peak visible but followed by multiple waves (+3 / -2 mV)
respiration ok
EDA ~8 microS, slightly noisy after entering scan , responsive to fist test

### task-friends_run-01 segment

s07e17a

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-01 notes

validation pre-run had low score for 80%conf metric, so RA did calbration/validation a second time

### task-friends_run-02 completion

- [ ] series was completed.

### task-friends_run-03 completion

- [ ] series was completed.

### task-friends_run-04 completion

- [ ] series was completed.

### task-friends_run-05 completion

- [ ] series was completed.

### task-friends_run-06 completion

- [ ] series was completed.

### task-friends_run-07 completion

- [ ] series was completed.

### task-friends_run-08 completion

- [ ] series was completed.

### task-friends_run-09 completion

- [ ] series was completed.

### task-friends_run-10 completion

- [ ] series was completed.
