### ISSUE TITLE
[SCAN] sub-01_ses-088

### ISSUE THREAD

**Issue by maelleF** [courtois-neuromod/friends#95]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

PPG ok
ECG ok, with occasional noise (+4mv / -2mv, r peak visible)
respiration ok
EDA ok, ~17 microS during setup, dropped to ~13 microS in scanner. test fist responsive

### task-friends_run-01 segment

s07e18b

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-01 notes

RA had not the psychopy window selected when starting the run, resulting with 20-30s with no stimuli displayed during the beginning scan. When RA realized the mistake, the scan was stopped (<1 min). Subject redid calibration/validation before staring the run again. 

subject seems to have moved his head during the run, with an important shift (median distance metric for the validation post run shows scores between 13 and 24)

### task-friends_run-02 segment

s07e19a

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-03 segment

s07e19b

### task-friends_run-03 completion

- [X] series was completed.

### task-friends_run-03 notes

by mistake, RA ended the session during the validation post-run.

### task-friends_run-04 completion

- [ ] series was completed.

### task-friends_run-05 completion

- [ ] series was completed.

### task-friends_run-06 completion

- [ ] series was completed.

### task-friends_run-07 completion

- [ ] series was completed.

### task-friends_run-08 completion

- [ ] series was completed.

### task-friends_run-09 completion

- [ ] series was completed.

### task-friends_run-10 completion

- [ ] series was completed.
