### ISSUE TITLE
[SCAN] sub-05_ses-053

### ISSUE THREAD

**Issue by RainyFields** [courtois-neuromod/friends#96]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

eyetracker callibration
pupil detection: mostly A
>70% confidence: mostly B
80% confidence: mostly C
distance:  all A

### task-friends_run-01 segment

e13a

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-02 segment

e13b

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-03 segment

e14a

### task-friends_run-03 completion

- [X] series was completed.

### task-friends_run-04 segment

e14b

### task-friends_run-04 completion

- [X] series was completed.

### task-friends_run-05 completion

- [ ] series was completed.

### task-friends_run-06 completion

- [ ] series was completed.

### task-friends_run-07 completion

- [ ] series was completed.

### task-friends_run-08 completion

- [ ] series was completed.

### task-friends_run-09 completion

- [ ] series was completed.

### task-friends_run-10 completion

- [ ] series was completed.
