### ISSUE TITLE
[SCAN] sub-01_ses-090

### ISSUE THREAD

**Issue by me-pic** [courtois-neuromod/friends#98]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

**During setup**
PPG, ECG, RSP ok
EDA electrodes didn't enough gel (signal amplitude near 0). After replacing the electrodes, signal around 8-9 microsiemens, but still noisy
EDA gain was set at 2

### task-friends_run-01 segment

s07e21a

### task-friends_run-01 completion

- [X] series was completed.

### task-friends_run-01 notes

**Eye-tracker calibration**
Some Cs for confidence; during the calibration the eyelid covered the pupil a little bit... RA decided to continue with the run.

**Physio**
Overall, R peaks visible on the ECG waveform
PPG ok
RSP ok
Few SCRs in EDA signal (amplitude around 7 microsiemens)

### task-friends_run-02 segment

s07e21b

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-02 notes

**Eye-tracker calibration**
Some Bs for confidence, but mostly As elsewhere
*During eyetracker calibration at the end of the run: participant had their eyes closed

**Physio**
PPG ok
Some sporadic noise in RSP signal
ECG a bit more noisy compared to previous run
Few SCRs in EDA

### task-friends_run-03 segment

s07e22a

### task-friends_run-03 completion

- [X] series was completed.

### task-friends_run-03 notes

**Eye-tracker calibration**
Mostly As and Bs
At some point: eyelid was covering top of the pupil leading to high uncertainty in pupil detection

**Physio**
PPG and RSP ok
ECG a bit noisy; but R peaks overall visible
Some SCRs 

### task-friends_run-04 segment

s07e22b

### task-friends_run-04 completion

- [X] series was completed.

### task-friends_run-04 notes

**Eye-tracker calibration**
Mostly As

**Physio**
Amplitude of PPG seemed to have decreased compared to previous runs
ECG noisy, but overall distinguishable R peaks
RSP ok
Amplitude of EDA waveform decreased a little bit (around 6 microsiemens); some SCRs
Towards the beginning and towards the end of the run, physio signals got noisy for few seconds potentially due to movements

### task-friends_run-05 completion

- [ ] series was completed.

### task-friends_run-06 completion

- [ ] series was completed.

### task-friends_run-07 completion

- [ ] series was completed.

### task-friends_run-08 completion

- [ ] series was completed.

### task-friends_run-09 completion

- [ ] series was completed.

### task-friends_run-10 completion

- [ ] series was completed.
