### ISSUE TITLE
[SCAN] sub-05_ses-054

### ISSUE THREAD

**Issue by RainyFields** [courtois-neuromod/friends#99]
### Setup

- [X] biopac
- [X] sensimetrics
- [X] eyetracker

### general notes

almost all As for eye calibration

### task-friends_run-01 segment

e15a

### task-friends_run-01 completion

- [ ] series was completed.

### task-friends_run-01 notes

by the end of the run for distance all Cs for the callibration

### task-friends_run-02 segment

e15b

### task-friends_run-02 completion

- [X] series was completed.

### task-friends_run-02 notes

callibration with mostly As

### task-friends_run-03 segment

e16a

### task-friends_run-03 completion

- [X] series was completed.

### task-friends_run-04 completion

- [ ] series was completed.

### task-friends_run-05 completion

- [ ] series was completed.

### task-friends_run-06 completion

- [ ] series was completed.

### task-friends_run-07 completion

- [ ] series was completed.

### task-friends_run-08 completion

- [ ] series was completed.

### task-friends_run-09 completion

- [ ] series was completed.

### task-friends_run-10 completion

- [ ] series was completed.
